# The configurations you want to execute
# That is, a combination of operating system and python version
# Please add or remove for your needs.
# Check all possible values for python in here: https://docs.travis-ci.com/user/languages/python/
# See how to further configure the matrix of combinations in here: https://docs.travis-ci.com/user/multi-os/
language: python

cache: pip

# Uncomment if you need super powers (e.g., for apt-get)
# sudo: require

# To use other python versions in osx, set the PYTHON variable with the version supported by pyenv.
# Check available versions with `pyenv install --list'.
matrix:
    include:
        - os: linux
          python: 3.5

# Command to install dependencies for each configuration.
install:
# For OSX, you may want to call a script installing virtual env and so on.
  - ./scripts/install.sh
  - pip install -U pytest
  - CI=false pip install .

# Command to run tests. These are run for each configuration
script:
  - python --version
  - pytest
